import {
  Album,
  ArrowDown,
  ArrowLeft,
  ArrowLeftSquare,
  BookPlus,
  BookUp,
  Eye,
  EyeOff,
  Filter,
  FileClock,
  FileStack,
  Home,
  Lock,
  Library,
  Mail,
  MoonIcon,
  Plus,
  SunIcon,
  Search,
  UserCircle2,
  X,
} from "lucide-react";

export const Icons = {
  album: Album,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowLeftSquare: ArrowLeftSquare,
  bookPlus: BookPlus,
  bookUp: BookUp,
  hide: Eye,
  view: EyeOff,
  filter: Filter,
  fileClock: FileClock,
  fileStack: FileStack,
  lock: Lock,
  library: Library,
  mail: Mail,
  moon: MoonIcon,
  plus: Plus,
  sun: SunIcon,
  search: Search,
  userCircle: UserCircle2,
  close: X,
  home: Home,
};
